name: Metrics Generator

on:
  schedule:
    - cron: '0 0 * * *' # Automatické spuštění jednou denně
  workflow_dispatch: # Ruční spuštění

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Metrics generator
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: alfacentaur1
